action_id: trunk-share-with-everyone
date: 2023-12-06 10:00:18
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1701856818
full_timestamp:
  nanos: 556949000
  seconds: 1701856818
trunk_version: 1.17.2
